// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.10.1
// source: msg.proto

package coozer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request_Verb int32

const (
	Request_NIL    Request_Verb = 0 // Place holder because the first enum value must be zero in proto3
	Request_GET    Request_Verb = 1
	Request_SET    Request_Verb = 2
	Request_DEL    Request_Verb = 3
	Request_REV    Request_Verb = 5
	Request_WAIT   Request_Verb = 6
	Request_NOP    Request_Verb = 7
	Request_WALK   Request_Verb = 9
	Request_GETDIR Request_Verb = 14
	Request_STAT   Request_Verb = 16
	Request_SELF   Request_Verb = 20
	Request_ACCESS Request_Verb = 99
)

// Enum value maps for Request_Verb.
var (
	Request_Verb_name = map[int32]string{
		0:  "NIL",
		1:  "GET",
		2:  "SET",
		3:  "DEL",
		5:  "REV",
		6:  "WAIT",
		7:  "NOP",
		9:  "WALK",
		14: "GETDIR",
		16: "STAT",
		20: "SELF",
		99: "ACCESS",
	}
	Request_Verb_value = map[string]int32{
		"NIL":    0,
		"GET":    1,
		"SET":    2,
		"DEL":    3,
		"REV":    5,
		"WAIT":   6,
		"NOP":    7,
		"WALK":   9,
		"GETDIR": 14,
		"STAT":   16,
		"SELF":   20,
		"ACCESS": 99,
	}
)

func (x Request_Verb) Enum() *Request_Verb {
	p := new(Request_Verb)
	*p = x
	return p
}

func (x Request_Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (Request_Verb) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x Request_Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Verb.Descriptor instead.
func (Request_Verb) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0, 0}
}

type Response_Err int32

const (
	Response_NIL          Response_Err = 0 // Place holder because the first enum value must be zero in proto3
	Response_OTHER        Response_Err = 127
	Response_TAG_IN_USE   Response_Err = 1
	Response_UNKNOWN_VERB Response_Err = 2
	Response_READONLY     Response_Err = 3
	Response_TOO_LATE     Response_Err = 4
	Response_REV_MISMATCH Response_Err = 5
	Response_BAD_PATH     Response_Err = 6
	Response_MISSING_ARG  Response_Err = 7
	Response_RANGE        Response_Err = 8
	Response_NOTDIR       Response_Err = 20
	Response_ISDIR        Response_Err = 21
	Response_NOENT        Response_Err = 22
)

// Enum value maps for Response_Err.
var (
	Response_Err_name = map[int32]string{
		0:   "NIL",
		127: "OTHER",
		1:   "TAG_IN_USE",
		2:   "UNKNOWN_VERB",
		3:   "READONLY",
		4:   "TOO_LATE",
		5:   "REV_MISMATCH",
		6:   "BAD_PATH",
		7:   "MISSING_ARG",
		8:   "RANGE",
		20:  "NOTDIR",
		21:  "ISDIR",
		22:  "NOENT",
	}
	Response_Err_value = map[string]int32{
		"NIL":          0,
		"OTHER":        127,
		"TAG_IN_USE":   1,
		"UNKNOWN_VERB": 2,
		"READONLY":     3,
		"TOO_LATE":     4,
		"REV_MISMATCH": 5,
		"BAD_PATH":     6,
		"MISSING_ARG":  7,
		"RANGE":        8,
		"NOTDIR":       20,
		"ISDIR":        21,
		"NOENT":        22,
	}
)

func (x Response_Err) Enum() *Response_Err {
	p := new(Response_Err)
	*p = x
	return p
}

func (x Response_Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Err) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[1].Descriptor()
}

func (Response_Err) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[1]
}

func (x Response_Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Err.Descriptor instead.
func (Response_Err) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag      int32        `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Verb     Request_Verb `protobuf:"varint,2,opt,name=verb,proto3,enum=coozer.Request_Verb" json:"verb,omitempty"`
	Path     string       `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Value    []byte       `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	OtherTag int32        `protobuf:"varint,6,opt,name=other_tag,json=otherTag,proto3" json:"other_tag,omitempty"`
	Offset   int32        `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	Rev      int64        `protobuf:"varint,9,opt,name=rev,proto3" json:"rev,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Request) GetVerb() Request_Verb {
	if x != nil {
		return x.Verb
	}
	return Request_NIL
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Request) GetOtherTag() int32 {
	if x != nil {
		return x.OtherTag
	}
	return 0
}

func (x *Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Request) GetRev() int64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag       int32        `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Flags     int32        `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Rev       int64        `protobuf:"varint,3,opt,name=rev,proto3" json:"rev,omitempty"`
	Path      string       `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Value     []byte       `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Len       int32        `protobuf:"varint,8,opt,name=len,proto3" json:"len,omitempty"`
	ErrCode   Response_Err `protobuf:"varint,100,opt,name=err_code,json=errCode,proto3,enum=coozer.Response_Err" json:"err_code,omitempty"`
	ErrDetail string       `protobuf:"bytes,101,opt,name=err_detail,json=errDetail,proto3" json:"err_detail,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Response) GetFlags() int32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Response) GetRev() int64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *Response) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Response) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Response) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *Response) GetErrCode() Response_Err {
	if x != nil {
		return x.ErrCode
	}
	return Response_NIL
}

func (x *Response) GetErrDetail() string {
	if x != nil {
		return x.ErrDetail
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6f,
	0x7a, 0x65, 0x72, 0x22, 0xb4, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x28, 0x0a, 0x04, 0x76, 0x65, 0x72, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x63, 0x6f, 0x6f, 0x7a, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x56, 0x65, 0x72, 0x62, 0x52, 0x04, 0x76, 0x65, 0x72, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x76, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x76, 0x22, 0x7c, 0x0a, 0x04,
	0x56, 0x65, 0x72, 0x62, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x47, 0x45, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x44, 0x45, 0x4c, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x45, 0x56, 0x10,
	0x05, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x4e,
	0x4f, 0x50, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x4c, 0x4b, 0x10, 0x09, 0x12, 0x0a,
	0x0a, 0x06, 0x47, 0x45, 0x54, 0x44, 0x49, 0x52, 0x10, 0x0e, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54,
	0x41, 0x54, 0x10, 0x10, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x46, 0x10, 0x14, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x63, 0x22, 0x88, 0x03, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65,
	0x76, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x12, 0x2f, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x63, 0x6f, 0x6f, 0x7a, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x65, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0xb5, 0x01,
	0x0a, 0x03, 0x45, 0x72, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x7f, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x41, 0x47,
	0x5f, 0x49, 0x4e, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x56, 0x45, 0x52, 0x42, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x41, 0x44, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x4f, 0x4f,
	0x5f, 0x4c, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x56, 0x5f, 0x4d,
	0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x41, 0x44,
	0x5f, 0x50, 0x41, 0x54, 0x48, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x49, 0x53, 0x53, 0x49,
	0x4e, 0x47, 0x5f, 0x41, 0x52, 0x47, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x41, 0x4e, 0x47,
	0x45, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x44, 0x49, 0x52, 0x10, 0x14, 0x12,
	0x09, 0x0a, 0x05, 0x49, 0x53, 0x44, 0x49, 0x52, 0x10, 0x15, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f,
	0x45, 0x4e, 0x54, 0x10, 0x16, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msg_proto_goTypes = []interface{}{
	(Request_Verb)(0), // 0: coozer.Request.Verb
	(Response_Err)(0), // 1: coozer.Response.Err
	(*Request)(nil),   // 2: coozer.Request
	(*Response)(nil),  // 3: coozer.Response
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: coozer.Request.verb:type_name -> coozer.Request.Verb
	1, // 1: coozer.Response.err_code:type_name -> coozer.Response.Err
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
